=== hmrc/external-message-adapter/conf/schemas/email_bounce_back_API_5951_schema_v1.0.2.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "emailAddress": {
      "format": "email",
      "description": "Email address associated with the bounced communication.",
      "maxLength": 320,
      "pattern": "^[^@\\s]{1,64}@[^@\\s]{1,255}$",
      "type": "string",
      "example": "someEmail@test.com"
    },
    "externalRefId": {
      "description": "External reference identifier supplied by the caller.",
      "maxLength": 40,
      "pattern": "^[^\\s]{1,40}$",
      "type": "string",
      "example": "9d7f1d67-5d54-4b00-9d6c-3a8f7fb2e1c4"
    },
    "formId": {
      "description": "Identifier of the form associated with the request.",
      "maxLength": 30,
      "pattern": "^.{0,30}$",
      "type": "string",
      "example": "SA300"
    },
    "properties": {
      "description": "Optional collection of additional processing properties.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/PropertyWrapper"
      }
    },
    "reason": {
      "description": "Reason for generating the bounceback communication.",
      "maxLength": 25,
      "pattern": "^[^\\s]{1,25}$",
      "type": "string",
      "example": "EMAIL_BOUNCE"
    },
    "sourceData": {
      "description": "Base64 encoded source payload. Max 10Kb when decoded.",
      "maxLength": 13656,
      "pattern": "^(?=.{1,13656}$)(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$",
      "type": "string",
      "example": "SGVsbG8gd29ybGQ="
    }
  },
  "required": [
    "externalRefId",
    "reason",
    "sourceData",
    "emailAddress"
  ],
  "definitions": {
    "PropertyWrapper": {
      "required": [
        "property"
      ],
      "type": "object",
      "properties": {
        "property": {
          "$ref": "#/definitions/Property"
        }
      }
    },
    "Property": {
      "type": "object",
      "properties": {
        "name": {
          "maxLength": 25,
          "pattern": "^.{0,25}$",
          "type": "string"
        },
        "value": {
          "maxLength": 25,
          "pattern": "^.{0,25}$",
          "type": "string",
          "example": "true"
        }
      },
      "required": [
        "name",
        "value"
      ]
    }
  }
}

=== hmrc/external-message-adapter/test/resources/email_bounce_back_request_valid.json
{
  "externalRefId": "9d7f1d67-5d54-4b00-9d6c-3a8f7fb2e1c4",
  "formId": "SA300",
  "properties": [
    {
      "property": {
        "name": "printedVariant",
        "value": "true"
      }
    },
    {
      "property": {
        "name": "printedVariant1",
        "value": "false"
      }
    }
  ],
  "reason": "EMAIL_BOUNCE",
  "sourceData": "SGVsbG8gd29ybGQ=",
  "emailAddress": "someEmail@test.com"
}
